name: dolftax's weblog!
url: http://dolftax.com
tagline:
location:
twitter: http://twitter.com/dolftax
github: https://github.com/dolftax
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:title
